# Generated by Django 4.0.4 on 2022-05-01 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('nombre_club', models.CharField(max_length=50, verbose_name='Nombre club')),
                ('temporada', models.CharField(max_length=20, verbose_name='Temporada')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('domicilio', models.CharField(max_length=50, verbose_name='Domicilio')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('codigo_postal', models.CharField(max_length=50, verbose_name='Código postal')),
                ('cod_club', models.CharField(max_length=50, verbose_name='Código club')),
                ('cod_equipo', models.CharField(max_length=50, verbose_name='Código equipo')),
                ('cod_temporada', models.CharField(max_length=50, verbose_name='Código temporada')),
                ('cod_grupo', models.CharField(max_length=50, verbose_name='Código grupo')),
                ('cod_competicion', models.CharField(max_length=50, verbose_name='Código competicion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('texto', models.TextField(max_length='500', verbose_name='Texto')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo')),
            ],
        ),
    ]
