# Generated by Django 4.0.4 on 2022-04-29 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('domicilio', models.CharField(max_length=50, verbose_name='Domicilio')),
                ('codigo_postal', models.CharField(max_length=50, verbose_name='Codigo postal')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('temporada', models.CharField(max_length=20, verbose_name='Temporada')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
