# Generated by Django 4.0.4 on 2022-05-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='creado_manual',
            field=models.BooleanField(default=False, verbose_name='Creado manualmente'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='cod_club',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código club'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='cod_competicion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código competicion'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='cod_equipo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código equipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='cod_grupo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código grupo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='cod_temporada',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código temporada'),
        ),
    ]
