# Generated by Django 4.0.4 on 2022-04-29 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(default=datetime.date(2022, 4, 29), verbose_name='Fecha de creación')),
                ('texto', models.TextField(max_length='500', verbose_name='Texto')),
            ],
        ),
    ]
