# Generated by Django 4.0.4 on 2022-04-29 15:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
