# Generated by Django 4.0.4 on 2022-05-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_creado_manual_alter_equipo_cod_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='texto',
            field=models.TextField(verbose_name='Texto'),
        ),
    ]
